# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_new_country.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_country(object):
    def setupUi(self, Dialog_country):
        Dialog_country.setObjectName("Dialog_country")
        Dialog_country.resize(427, 172)
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        Dialog_country.setFont(font)
        self.label_new_country = QtWidgets.QLabel(Dialog_country)
        self.label_new_country.setGeometry(QtCore.QRect(90, 10, 261, 41))
        self.label_new_country.setObjectName("label_new_country")
        self.button_new_country = QtWidgets.QPushButton(Dialog_country)
        self.button_new_country.setGeometry(QtCore.QRect(160, 120, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(14)
        self.button_new_country.setFont(font)
        self.button_new_country.setObjectName("button_new_country")
        self.input_new_country = QtWidgets.QLineEdit(Dialog_country)
        self.input_new_country.setGeometry(QtCore.QRect(50, 60, 331, 41))
        self.input_new_country.setObjectName("input_new_country")

        self.retranslateUi(Dialog_country)
        QtCore.QMetaObject.connectSlotsByName(Dialog_country)

    def retranslateUi(self, Dialog_country):
        _translate = QtCore.QCoreApplication.translate
        Dialog_country.setWindowTitle(_translate("Dialog_country", "新增國家選項"))
        self.label_new_country.setText(_translate("Dialog_country", "請輸入要新增的國家 :"))
        self.button_new_country.setText(_translate("Dialog_country", "確認"))
